# Generated by Django 5.2.7 on 2025-10-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser_is_staff_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='ip_addresses',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_addresses',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
