# Generated by Django 5.2.7 on 2025-10-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historicaluser_ip_addresses_user_ip_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Indica si el email ha sido verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Indica si el email ha sido verificado'),
        ),
    ]
