#!/usr/bin/env bash
set -euo pipefail

_usage() {
  echo "developing"
  echo "    test          run test suites"
  echo ""
  echo "requirements"
  echo "    pipi          install python requirements based on requirements.txt"
  echo ""
  echo "migrations"
  echo "    migrate       run pending migrations"
  echo "    makemig       make django migrations"
  echo ""
  echo "tools"
  echo "    shell         enter the django shell"
  echo "    black         run black"
  echo "    isort         run isort"
  echo "    createapp     create django app"
  echo "    csuser        create a new superuser"
  echo "    static        collect static files"
  echo "    jupyter       start jupyter notebook server"
  echo "    shell_plus    start shell_plus the django proyect"
  echo "    collectstatic collect static files"

  exit 1
}

# show usage if no argument is given
arg=${1:-}
shift || _usage

case ${arg} in
test)
  pytest "$@" --isort --black
;;
cov)
  pytest "$@" --isort --black --cov=factorial_hr
;;
black)
  black .
;;
isort)
  isort .
;;
csuser)
  python manage.py createsuperuser
;;
createapp)
  mkdir ./factorial_hr/apps/"$@" &&
  python manage.py startapp "$@" ./factorial_hr/apps/"$@"
;;
pipi)
  pip install -r requirements.txt
;;
shell)
  python manage.py shell
;;
migrate)
  python manage.py migrate "$@"
;;
makemigrations|makemigration|makemig)
  python manage.py makemigrations "$@"
;;
static)
  python manage.py collectstatic
;;
jupyter)
  python manage.py shell_plus --notebook "$@"
;;
shell_plus)
  python manage.py shell_plus
;;
collectstatic)
  python manage.py collectstatic
;;
*)
  _usage
;;
esac